- block:
    - name: 'PULP | configuring pulp'
      lineinfile:
        dest:         "{{ pulp_conf }}"
        line:         "{{ item.key }}={{ item.value }}"
        state:        'present'
        regexp:       "^{{ item.key }}"
        backup:       true
      with_dict: "{{ pulp_settings }}"
      notify:    'restart pulp workers'
      tags:
        - always
